<?php
// auto-generated by sfLuceneProjectConfigHandler
// date: 2010/07/01 18:20:25

$config = array();



// processing  index now...
$config['index'] = array (
  'models' => 
  array (
    'FakeForum' => 
    array (
      'fields' => 
      array (
        'id' => 
        array (
          'type' => 'unindexed',
          'boost' => 1,
          'transform' => NULL,
          'multiValued' => false,
          'required' => false,
          'stored' => false,
          'default' => NULL,
          'alias' => NULL,
          'omitNorms' => false,
        ),
        'title' => 
        array (
          'type' => 'text',
          'boost' => 2,
          'transform' => NULL,
          'multiValued' => false,
          'required' => false,
          'stored' => false,
          'default' => NULL,
          'alias' => NULL,
          'omitNorms' => false,
        ),
        'description' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
          'multiValued' => false,
          'required' => false,
          'stored' => false,
          'default' => NULL,
          'alias' => NULL,
          'omitNorms' => false,
        ),
      ),
      'title' => 'title',
      'description' => 'description',
      'categories' => 
      array (
        0 => 'Forum',
      ),
      'route' => 'forum/showForum?id=%id%',
      'validator' => 'isIndexable',
      'rebuild_limit' => 5,
      'peer' => 'FakeForumPeer',
      'partial' => 'forumResult',
      'callback' => NULL,
      'indexer' => NULL,
    ),
  ),
  'index' => 
  array (
    'encoding' => 'UTF-8',
    'cultures' => 
    array (
      0 => 'en',
      1 => 'fr',
    ),
    'mb_string' => true,
    'param' => 
    array (
    ),
    'host' => 'localhost',
    'port' => '8983',
    'base_url' => '/solr',
  ),
  'interface' => 
  array (
    'categories' => true,
    'advanced' => true,
  ),
  'factories' => 
  array (
    'indexers' => 
    array (
    ),
    'results' => 
    array (
    ),
  ),
);


// processing  fooLucene now...
$config['fooLucene'] = array (
  'index' => 
  array (
    'encoding' => 'utf-8',
    'cultures' => 
    array (
      0 => 'en',
    ),
    'mb_string' => false,
    'param' => 
    array (
    ),
    'host' => 'localhost',
    'port' => '8983',
    'base_url' => '/solr',
  ),
  'models' => 
  array (
  ),
  'factories' => 
  array (
    'indexers' => 
    array (
    ),
    'results' => 
    array (
    ),
  ),
);
