<?php
// auto-generated by sfLuceneProjectConfigHandler
// date: 2009/11/18 00:22:20

$config = array();



// processing  index now...
$config['index'] = array (
  'models' => 
  array (
    'FakeForum' => 
    array (
      'fields' => 
      array (
        'id' => 
        array (
          'type' => 'unindexed',
          'boost' => 1,
          'transform' => NULL,
          'multiValued' => false,
          'required' => false,
          'stored' => false,
        ),
        'title' => 
        array (
          'type' => 'text',
          'boost' => 2,
          'transform' => NULL,
          'multiValued' => false,
          'required' => false,
          'stored' => false,
        ),
        'description' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
          'multiValued' => false,
          'required' => false,
          'stored' => false,
        ),
      ),
      'title' => 'title',
      'description' => 'description',
      'categories' => 
      array (
        0 => 'Forum',
      ),
      'route' => 'forum/showForum?id=%id%',
      'validator' => 'isIndexable',
      'rebuild_limit' => 5,
      'peer' => 'FakeForumPeer',
      'partial' => 'forumResult',
      'indexer' => NULL,
    ),
  ),
  'index' => 
  array (
    'encoding' => 'UTF-8',
    'cultures' => 
    array (
      0 => 'en',
      1 => 'fr',
    ),
    'stop_words' => 
    array (
      0 => 'and',
      1 => 'the',
    ),
    'short_words' => 2,
    'analyzer' => 'utf8num',
    'case_sensitive' => false,
    'mb_string' => true,
    'param' => 
    array (
    ),
    'host' => 'localhost',
    'port' => '8983',
    'base_url' => '/solr',
  ),
  'interface' => 
  array (
    'categories' => true,
    'advanced' => true,
  ),
  'factories' => 
  array (
    'indexers' => 
    array (
    ),
    'results' => 
    array (
    ),
  ),
);


// processing  fooLucene now...
$config['fooLucene'] = array (
  'index' => 
  array (
    'encoding' => 'utf-8',
    'cultures' => 
    array (
      0 => 'en',
    ),
    'stop_words' => 
    array (
      0 => 'a',
      1 => 'an',
      2 => 'at',
      3 => ' the',
      4 => 'and',
      5 => 'or',
      6 => 'is',
      7 => 'am',
      8 => 'are',
      9 => 'of',
    ),
    'short_words' => 2,
    'analyzer' => 'textnum',
    'case_sensitive' => false,
    'mb_string' => false,
    'param' => 
    array (
    ),
    'host' => 'localhost',
    'port' => '8983',
    'base_url' => '/solr',
  ),
  'models' => 
  array (
  ),
  'factories' => 
  array (
    'indexers' => 
    array (
    ),
    'results' => 
    array (
    ),
  ),
);
