<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/11/18 00:22:13
return array(
'current_route' => new sfRoute('/lucene/search', array (
  'module' => 'sfLucene',
  'action' => 'search',
), array (
), array (
)),
);
